# Generated by Django 4.0.3 on 2025-12-06 07:33

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='نام شرکت')),
                ('activity_field', models.CharField(max_length=255, verbose_name='حوزه فعالیت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'شرکت',
                'verbose_name_plural': 'شرکت\u200cها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CompanyDepartment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='نام بخش')),
                ('employee_count', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='تعداد کارکنان')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'بخش شرکت',
                'verbose_name_plural': 'بخش\u200cهای شرکت',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CompanyMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('position', models.CharField(choices=[('MANAGER', 'مدیر'), ('SUPERVISOR', 'ناظر'), ('EXPERT', 'کارشناس'), ('OPERATOR', 'اپراتور'), ('WORKER', 'کارگر'), ('OTHER', 'سایر')], default='WORKER', max_length=50, verbose_name='سمت')),
                ('status', models.CharField(choices=[('ACTIVE', 'فعال'), ('INACTIVE', 'غیرفعال'), ('SUSPENDED', 'تعلیق شده')], default='ACTIVE', max_length=50, verbose_name='وضعیت')),
                ('join_date', models.DateField(auto_now_add=True, verbose_name='تاریخ عضویت')),
                ('leave_date', models.DateField(blank=True, null=True, verbose_name='تاریخ ترک')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
            ],
            options={
                'verbose_name': 'عضو شرکت',
                'verbose_name_plural': 'اعضای شرکت',
                'ordering': ['-join_date'],
            },
        ),
        migrations.CreateModel(
            name='HSEReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='عنوان گزارش')),
                ('report_type', models.CharField(choices=[('MONTHLY', 'ماهانه'), ('QUARTERLY', 'فصلی'), ('YEARLY', 'سالانه'), ('INCIDENT', 'حادثه'), ('INSPECTION', 'بازرسی'), ('SAFETY', 'ایمنی'), ('ENVIRONMENTAL', 'محیط زیستی'), ('HEALTH', 'بهداشتی')], max_length=50, verbose_name='نوع گزارش')),
                ('period_start', models.DateField(verbose_name='شروع دوره')),
                ('period_end', models.DateField(verbose_name='پایان دوره')),
                ('total_incidents', models.IntegerField(default=0, verbose_name='تعداد کل حوادث')),
                ('serious_incidents', models.IntegerField(default=0, verbose_name='حوادث شدید')),
                ('minor_incidents', models.IntegerField(default=0, verbose_name='حوادث جزئی')),
                ('near_misses', models.IntegerField(default=0, verbose_name='شبه حوادث')),
                ('total_inspections', models.IntegerField(default=0, verbose_name='تعداد بازرسی\u200cها')),
                ('completed_inspections', models.IntegerField(default=0, verbose_name='بازرسی\u200cهای تکمیل شده')),
                ('pending_inspections', models.IntegerField(default=0, verbose_name='بازرسی\u200cهای در انتظار')),
                ('total_tasks', models.IntegerField(default=0, verbose_name='تعداد وظایف')),
                ('completed_tasks', models.IntegerField(default=0, verbose_name='وظایف تکمیل شده')),
                ('overdue_tasks', models.IntegerField(default=0, verbose_name='وظایف معوقه')),
                ('accident_frequency_rate', models.FloatField(default=0, verbose_name='نرخ فراوانی حوادث')),
                ('accident_severity_rate', models.FloatField(default=0, verbose_name='نرخ شدت حوادث')),
                ('safety_performance_index', models.FloatField(default=0, verbose_name='شاخص عملکرد ایمنی')),
                ('recommendations', models.TextField(blank=True, verbose_name='توصیه\u200cها')),
                ('conclusions', models.TextField(blank=True, verbose_name='نتیجه\u200cگیری')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
            ],
            options={
                'verbose_name': 'گزارش HSE',
                'verbose_name_plural': 'گزارشات HSE',
                'ordering': ['-period_end'],
            },
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='عنوان حادثه')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('incident_type', models.CharField(choices=[('OCCURRED', 'اتفاق افتاده'), ('POTENTIAL', 'احتمالی'), ('NEAR_MISS', 'شبه\u200cحادثه')], max_length=50, verbose_name='نوع حادثه')),
                ('severity_level', models.CharField(choices=[('LOW', 'پایین'), ('MEDIUM', 'متوسط'), ('HIGH', 'بالا'), ('SEVERE', 'شدید')], default='MEDIUM', max_length=50, verbose_name='سطح حادثه')),
                ('status', models.CharField(choices=[('UNDER_INVESTIGATION', 'در حال بررسی'), ('REPORTED', 'گزارش شده'), ('RESOLVED', 'حل شده'), ('CLOSED', 'بسته شده'), ('PENDING', 'در انتظار')], default='UNDER_INVESTIGATION', max_length=50, verbose_name='وضعیت حادثه')),
                ('incident_date', models.DateTimeField(verbose_name='تاریخ وقوع حادثه')),
                ('location', models.CharField(blank=True, max_length=500, verbose_name='محل وقوع')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
            ],
            options={
                'verbose_name': 'حادثه',
                'verbose_name_plural': 'حوادث',
                'ordering': ['-incident_date'],
            },
        ),
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='عنوان بازرسی')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('priority', models.CharField(choices=[('LOW', 'پایین'), ('MEDIUM', 'متوسط'), ('HIGH', 'بالا'), ('CRITICAL', 'بحرانی')], default='MEDIUM', max_length=50, verbose_name='الویت')),
                ('status', models.CharField(choices=[('DRAFT', 'پیش\u200cنویس'), ('IN_PROGRESS', 'در حال انجام'), ('UNDER_REVIEW', 'در حال بررسی'), ('COMPLETED', 'تکمیل شده'), ('CANCELLED', 'لغو شده')], default='DRAFT', max_length=50, verbose_name='وضعیت بازرسی')),
                ('scheduled_date', models.DateField(verbose_name='تاریخ برنامه\u200cریزی شده')),
                ('completed_date', models.DateField(blank=True, null=True, verbose_name='تاریخ تکمیل')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
            ],
            options={
                'verbose_name': 'بازرسی',
                'verbose_name_plural': 'بازرسی\u200cها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('position', models.CharField(choices=[('MANAGER', 'مدیر'), ('SUPERVISOR', 'ناظر'), ('EXPERT', 'کارشناس'), ('OPERATOR', 'اپراتور'), ('WORKER', 'کارگر'), ('OTHER', 'سایر')], default='WORKER', max_length=50, verbose_name='سمت پیشنهادی')),
                ('status', models.CharField(blank=True, choices=[('PENDING', 'در انتظار'), ('ACCEPTED', 'پذیرفته شده'), ('REJECTED', 'رد شده'), ('EXPIRED', 'منقضی شده')], default='PENDING', max_length=50, null=True, verbose_name='وضعیت')),
                ('message', models.TextField(blank=True, verbose_name='پیام دعوت')),
                ('token', models.CharField(max_length=100, unique=True, verbose_name='توکن')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('expires_at', models.DateTimeField(verbose_name='تاریخ انقضا')),
                ('responded_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ پاسخ')),
            ],
            options={
                'verbose_name': 'دعوت\u200cنامه',
                'verbose_name_plural': 'دعوت\u200cنامه\u200cها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('message', models.TextField(verbose_name='پیام')),
                ('notification_type', models.CharField(choices=[('INVITATION', 'دعوت'), ('TASK_ASSIGNED', 'وظیفه محول شده'), ('INSPECTION_REMINDER', 'یادآوری بازرسی'), ('INCIDENT_REPORT', 'گزارش حادثه'), ('SYSTEM', 'سیستمی'), ('WARNING', 'هشدار')], max_length=50, verbose_name='نوع اعلان')),
                ('is_read', models.BooleanField(default=False, verbose_name='خوانده شده')),
                ('related_object_id', models.UUIDField(blank=True, null=True, verbose_name='آیدی شی مرتبط')),
                ('related_object_type', models.CharField(blank=True, max_length=100, verbose_name='نوع شی مرتبط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
            ],
            options={
                'verbose_name': 'اعلان',
                'verbose_name_plural': 'اعلان\u200cها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='عنوان وظیفه')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('priority', models.CharField(choices=[('LOW', 'پایین'), ('MEDIUM', 'متوسط'), ('HIGH', 'بالا'), ('URGENT', 'فوری')], default='MEDIUM', max_length=50, verbose_name='الویت')),
                ('status', models.CharField(choices=[('PENDING', 'در انتظار'), ('IN_PROGRESS', 'در حال انجام'), ('UNDER_REVIEW', 'در حال بررسی'), ('COMPLETED', 'تکمیل شده'), ('CANCELLED', 'لغو شده')], default='PENDING', max_length=50, verbose_name='وضعیت')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='تاریخ سررسید')),
                ('completed_date', models.DateField(blank=True, null=True, verbose_name='تاریخ تکمیل')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to='hse.companymember', verbose_name='مسئول')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='hse.company', verbose_name='شرکت')),
            ],
            options={
                'verbose_name': 'وظیفه',
                'verbose_name_plural': 'وظایف',
                'ordering': ['-created_at'],
            },
        ),
    ]
