# Generated by Django 4.0.3 on 2025-12-06 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hse', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='invited_mobile',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='شماره موبایل دعوت شده'),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='status',
            field=models.CharField(choices=[('PENDING', 'در انتظار'), ('ACCEPTED', 'پذیرفته شده'), ('REJECTED', 'رد شده'), ('EXPIRED', 'منقضی شده')], default='PENDING', max_length=50, verbose_name='وضعیت'),
        ),
    ]
