# Generated by Django 4.0.3 on 2025-12-06 19:01

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hse', '0003_invitation_invited_mobile_alter_invitation_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='عنوان آموزش')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات آموزش')),
                ('training_type', models.CharField(choices=[('SAFETY', 'ایمنی'), ('ENVIRONMENTAL', 'محیط زیستی'), ('HEALTH', 'بهداشتی'), ('FIRE', 'اطفاء حریق'), ('FIRST_AID', 'کمک\u200cهای اولیه'), ('ERGONOMIC', 'ارگونومی'), ('CHEMICAL', 'مواد شیمیایی'), ('EQUIPMENT', 'تجهیزات')], max_length=50, verbose_name='نوع آموزش')),
                ('level', models.CharField(choices=[('BASIC', 'مقدماتی'), ('INTERMEDIATE', 'متوسط'), ('ADVANCED', 'پیشرفته')], default='BASIC', max_length=50, verbose_name='سطح آموزش')),
                ('status', models.CharField(choices=[('PLANNED', 'برنامه\u200cریزی شده'), ('IN_PROGRESS', 'در حال اجرا'), ('COMPLETED', 'تکمیل شده'), ('CANCELLED', 'لغو شده')], default='PLANNED', max_length=50, verbose_name='وضعیت آموزش')),
                ('video', models.FileField(blank=True, null=True, upload_to='trainings/videos/', verbose_name='فیلم آموزش')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='trainings/attachments/', verbose_name='ضمیمه')),
                ('duration_minutes', models.PositiveIntegerField(default=60, verbose_name='مدت زمان آموزش (دقیقه)')),
                ('scheduled_date', models.DateTimeField(verbose_name='تاریخ و زمان برنامه\u200cریزی')),
                ('completion_date', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ تکمیل')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainings', to='hse.company', verbose_name='شرکت')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_trainings', to=settings.AUTH_USER_MODEL, verbose_name='ایجاد کننده')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trainings', to='hse.companydepartment', verbose_name='بخش')),
                ('instructor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instructor_trainings', to='hse.companymember', verbose_name='مدرس')),
            ],
            options={
                'verbose_name': 'آموزش',
                'verbose_name_plural': 'آموزش\u200cها',
                'ordering': ['-scheduled_date'],
            },
        ),
        migrations.AlterField(
            model_name='inspection',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_inspections', to=settings.AUTH_USER_MODEL, verbose_name='ایجاد کننده'),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspections', to='hse.companydepartment', verbose_name='بخش'),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='priority',
            field=models.CharField(choices=[('LOW', 'پایین'), ('MEDIUM', 'متوسط'), ('HIGH', 'بالا'), ('CRITICAL', 'بحرانی')], default='MEDIUM', max_length=50, verbose_name='اولویت'),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='scheduled_date',
            field=models.DateField(verbose_name='تاریخ برنامه\u200cریزی'),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'پیش\u200cنویس'), ('IN_PROGRESS', 'در حال انجام'), ('COMPLETED', 'تکمیل شده')], default='DRAFT', max_length=50, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی'),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('LOW', 'پایین'), ('MEDIUM', 'متوسط'), ('HIGH', 'بالا'), ('URGENT', 'فوری')], default='MEDIUM', max_length=50, verbose_name='اولویت'),
        ),
        migrations.CreateModel(
            name='TrainingParticipation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('attendance_status', models.CharField(choices=[('REGISTERED', 'ثبت\u200cنام شده'), ('ATTENDED', 'حاضر شده'), ('ABSENT', 'غایب'), ('EXCUSED', 'معذور')], default='REGISTERED', max_length=50, verbose_name='وضعیت حضور')),
                ('participant_rating', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='امتیاز شرکت\u200cکننده (1-5)')),
                ('participant_feedback', models.TextField(blank=True, verbose_name='نظر شرکت\u200cکننده')),
                ('test_score', models.PositiveIntegerField(blank=True, null=True, verbose_name='نمره آزمون')),
                ('certificate_issued', models.BooleanField(default=False, verbose_name='صدور گواهی')),
                ('certificate_issue_date', models.DateField(blank=True, null=True, verbose_name='تاریخ صدور گواهی')),
                ('registered_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت\u200cنام')),
                ('attended_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ حضور')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_participations', to='hse.companymember', verbose_name='شرکت\u200cکننده')),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participation_records', to='hse.training', verbose_name='آموزش')),
            ],
            options={
                'verbose_name': 'حضور در آموزش',
                'verbose_name_plural': 'حضور در آموزش\u200cها',
                'unique_together': {('training', 'participant')},
            },
        ),
        migrations.AddField(
            model_name='training',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='participated_trainings', through='hse.TrainingParticipation', to='hse.companymember', verbose_name='شرکت\u200cکنندگان'),
        ),
        migrations.CreateModel(
            name='TrainingCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='نام دسته\u200cبندی')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_categories', to='hse.company', verbose_name='شرکت')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='hse.trainingcategory', verbose_name='دسته\u200cبندی والد')),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی آموزش',
                'verbose_name_plural': 'دسته\u200cبندی\u200cهای آموزش',
                'ordering': ['name'],
                'unique_together': {('company', 'name')},
            },
        ),
    ]
