# Generated by Django 4.0.3 on 2025-12-11 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hse', '0004_training_alter_inspection_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companydepartment',
            name='description',
            field=models.TextField(blank=True, verbose_name='توضیحات'),
        ),
    ]
